// Secao31-Angular9/frontend/src/app/views/home/home.component.ts
import { Component } from '@angular/core';
import { HeaderService } from '../../components/template/header/header.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent {
  constructor(private headerService: HeaderService) {
    headerService.headerData = {
      title: 'Início',
      icon: 'home',
      routeUrl: ''
    }
  }
}

<mat-card class="home mat-elevation-z3">
    <mat-card-title class="title">
        Bem vindo!
    </mat-card-title>
    <mat-card-subtitle class="subtitle">
        Sistema para exemplificar um CRUD em Angular
    </mat-card-subtitle>
</mat-card>

// Secao24-Projeto_Cadastro_de_Usuário/crud/frontend/src/components/home/home.jsx
import React from "react";
import Main from "../template/Main";

const Home = props => (
    <Main icon="home" title="Início"
        subtitle="Segundo projeto do capítulo de React.">
        <div className="display-4">Bem Vindo!</div>
        <hr />
        <p className="mb-0">Sistema para exemplificar a construção
        de um cadastro desenvolvido em React!</p>
    </Main>
)

export default Home
